### ISSUE TITLE
generate_poison_transformer.py-"IndexError: index 186 is out of bounds for dimension 0 with size 32"

### ISSUE THREAD

**Issue by huangxingseng** [UCDvision/backdoor_transformer#2]
I want using your code to generate poison sample of deit model, but i get the error about the feature size. can you help me?
The detail:
    ingletarget_1000class_finetune_deit_base/experiment_0001_base.cfg
2023-07-02 05:16:05,878 Experiment ID: 0001_base
2023-07-02 05:16:05,878 Use GPU: 0 for training
2023-07-02 05:16:05,878 => using pre-trained model 'deit_base'
2023-07-02 05:16:30,336 Using single source for this experiment.
2023-07-02 05:16:30,444 Number of target images:200
2023-07-02 05:16:30,444 Number of source images:200
Traceback (most recent call last):
  File "generate_poison_transformer.py", line 350, in <module>
    main()
  File "generate_poison_transformer.py", line 124, in main
    main_worker()
  File "generate_poison_transformer.py", line 149, in main_worker
    train(model, epoch)
  File "generate_poison_transformer.py", line 287, in train
    feat1[dist_min_index[1]] = feat11[dist_min_index[0]]
IndexError: index 186 is out of bounds for dimension 0 with size 32

**Comment by Kelo2000** [comment]
Hi! Did you figure out a solution for this issue?

**Comment by clpoz** [comment]
> Hi! Did you figure out a solution for this issue?

Same questions
